<h1 style="color: red; text-align:center;"> Numpy.</h1>

<p>Numpy es una libreria de python, la cual provee con manejo de arreglos multi-dimencionales que pueden ser usados como matrices o vectores.</p>
<p>Caracteristicas de numpy:</p>
<p>* n arreglos: arreglos de n dimencion, del mismo tipo de datos los cuales son eficientes en terminos de espacio y rapidez. Existen metodos para crear narreglos, los cuales nos permiten un rapido proceso de datos sin necesidad de usar loops.</p>
<p>* Broadcasting: Una herramienta que define implicitamente el comportamiento entre arreglos multidimencionales de diferentes tamaños.</p>
<p>* Vectorizacion: Permite realizar operaciones numericas entre narreglos</p>
<p>* Input/Output: Escritura y lectura simple de data en un archivo.</p>

<h5>Empezando con narreglos</h5>

<p>Creando arreglos de n rango.</p>

In [1]:
import numpy as np

In [2]:
#Creando arreglo de rango 1

un_arreglo =  np.array([1, 11, 111])
print(un_arreglo)
print(type(un_arreglo))

[  1  11 111]
<class 'numpy.ndarray'>


In [3]:
#Probando la forma del arreglo recien creado. Deberia ser de 1 dimencion

print(un_arreglo.shape)

(3,)


In [5]:
#Como es un arreglo de rango 1, solo necesitamos acceder por un indice

print(un_arreglo[0], un_arreglo[1], un_arreglo[2])

1 11 111


In [6]:
#Los narreglos son editables, ejemplo de un cambio.

un_arreglo[0] = 99
print(un_arreglo)

[ 99  11 111]


<p>Como crear arreglos de rango 2.</p>
<p>Un arreglo de rango 2 es un arreglo que posee 2 dimenciones.</p>

In [9]:
otro_arreglo = np.array([[11,12,13], [14,15,16]])

print(otro_arreglo)

print("La forma es dos filas y tres columnas: ", otro_arreglo.shape)

print("Accediendo a los elementos de [0,0], [0,1], [1,0]: ", otro_arreglo[0,0], ", ", otro_arreglo[0,1], ", ", otro_arreglo[1,0])

[[11 12 13]
 [14 15 16]]
La forma es dos filas y tres columnas:  (2, 3)
Accediendo a los elementos de [0,0], [0,1], [1,0]:  11 ,  12 ,  14


<p>Hay varias maneras de crear arreglos con numpy. Numpy tiene una variedad de metodos que nos ayudan a crear rapidamente arreglos multidimencionales.</p>

In [1]:
import numpy as np

In [3]:
#Crear un arreglo de 2x2 de ceros.

ej1 = np.zeros((2,2))
print(ej1)

[[0. 0.]
 [0. 0.]]


In [4]:
#Crear un arreglo de 2x2 de nueves.

ej2 = np.full((2,2), 9.0)
print(ej2)

[[9. 9.]
 [9. 9.]]


In [5]:
#crear una matriz diagonal de 2x2.
ej3 = np.eye(2,2)
print(ej3)

[[1. 0.]
 [0. 1.]]


In [6]:
#Crear un arreglo de unos.

ej4 = np.ones((1,2))
print(ej4)

[[1. 1.]]


In [8]:
#Prestar atencion en el arreglo de arriva (ej4), que es un arreglo de rango 2, 2x1
print(ej4.shape)

#Lo que significa que debemos usar 2 indices para acceder a los elementos.
print("-" * 30)
print(ej4[0,1])

(1, 2)
------------------------------
1.0


In [9]:
#Crear un arreglo de numeros randoms entre 0 y 1.

ej5 = np.random.random((2,2))
print(ej5)

[[0.31285389 0.93068169]
 [0.95560904 0.04800592]]


<h5>Recortar arreglos mediante "slice indexing".</h5>
<p>Similar a cuando se recortan listas o cadenas de texto, se pueden recortar narreglos para acceder a subregiones especificas.</p>

In [1]:
import numpy as np

In [20]:
#Arreglo de rango 2, de la forma (3, 4): 3 filas, 4 columnas

matriz = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(matriz)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [21]:
#Usar slicing para obtener una submatriz de 2x2

submatriz = matriz[:2, 1:3]
print(submatriz)

[[12 13]
 [22 23]]


<p>Cuando se modifica un slice, en realidad se modifica toda la matriz subyacente.</p>

In [22]:
#Miramos el elemento de 0,1
print("Antes: ", matriz[0,1])

#Cambiamos el mismo elemento seleccionado arriba, pero en la submatriz creada.
submatriz[0,0] = 100

#Miramos el mismo elemento seleccionado de la matriz.
print("Despues: ", matriz[0,1])

Antes:  12
Despues:  100


<p>Se puede combinar la indexacion y slice para crear matrices de diferentes formas.</p>

In [23]:
#Crear un arreglod e rango 2 de la forma(3,4)

un_arreglo = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(un_arreglo)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [24]:
#Usando indexing y slicing para generar un arreglo de rango menor
row_rank1 = un_arreglo[1, :]

print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [31]:
#Podemos hacer lo mismo para columnas de nuestro arreglo

col_rank1 = un_arreglo[:, 1]
col_rank2 = un_arreglo[:, 1:2]

print(col_rank1, col_rank1.shape)
print("-" * 30)
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)
------------------------------
[[12]
 [22]
 [32]] (3, 1)


<p>Indexando arreglo para cambiar elementos.</p>

In [32]:
#Creando un nuevo arreglo

arreglo = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print("Arreglo original: ")
print(arreglo)

Arreglo original: 
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [33]:
#Creando un arreglo de indices
col_indices = np.array([0,1,2,0])
print("\nCol indices elegidos: ", col_indices)

row_indices = np.arange(4)
print("\nFilas indices elegidos: ", row_indices)


Col indices elegidos:  [0 1 2 0]

Filas indices elegidos:  [0 1 2 3]


In [36]:
#Examinar los pares de row_indices y col_indices. Son los valores que se van a cambiar.
for row,col in zip(row_indices, col_indices):
    print(row, ", ", col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [38]:
#Seleccionar un elemento de cada fila
print(arreglo)
print("-" * 40)

print("Valores en el arreglo con estos indices", arreglo[row_indices, col_indices])

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
----------------------------------------
Valores en el arreglo con estos indices [11 22 33 41]


In [39]:
#Cambiar un elemento de cada fila usando los indices seleccionados

arreglo[row_indices, col_indices] += 100000
print(arreglo)

[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


<h2 style="color: purple;">Indexacion booleana.</h2>

In [3]:
#Crear un arreglo de 3x2
arreglo = np.array([[11,12], [21,22], [31,32]])
print(arreglo)

[[11 12]
 [21 22]
 [31 32]]


In [41]:
#Crear un filtro que seran valores booleandos tales que se cumpla la condicion.

filtro = (arreglo > 15)
filtro

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [42]:
#Ahora podemos seleccionar los valores que se corresponden con la condicion

print(arreglo[filtro])

[21 22 31 32]


In [43]:
#Una forma corta de hacerlo:
arreglo[arreglo > 15]

array([21, 22, 31, 32])

<p>Podemos cambiar elementos de un arreglo usando la misma logica.</p>

In [4]:
arreglo[arreglo % 2 == 0] += 100
print(arreglo)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


<h5>Tipos de datos y operaciones de arreglos.</h5>

In [5]:
#Python asigna el tipo de dato

ej1 = np.array([11,12])
print(ej1.dtype)

int32


In [6]:
#Python asigna el tipo de dato

ej2 = np.array([11.0,12.0])
print(ej2.dtype)

float64


In [7]:
#nosotros asignamos el tipo de dato.

ej3 = np.array([11,21], dtype=np.int64)
print(ej3.dtype)

int64


In [9]:
#Se puede usar la asignacion de tipo de dato para forzar numeros enteros

ej4 = np.array([11.1,12.7], dtype = np.int64)
print(ej4.dtype)
print()
print(ej4)

int64

[11 12]


In [4]:
#Tambien se puede usar el dtype para forzar numeros enteros a numeros con coma(flotantes)

ej5 = np.array([11, 21], dtype=np.float64)
print(ej5.dtype)
print(ej5)

float64
[11. 21.]


<h5>Operaciones aritmeticas con arreglos.</h5>

In [6]:
x = np.array([[111,112], [121, 122]], dtype=np.int)
y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [7]:
#suma de matrices

print(x + y)
print()
print(np.add(x, y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [8]:
#Resta de matrices

print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [9]:
#Multiplicacion de matrices

print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [10]:
#Division de matrices

print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [11]:
#Raiz cuadrada de una matriz (elemento a elemento)

print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [12]:
#Exponencial (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<h5>Metodos estadisticos, de ordenamiento y operaciones de conjuntos.</h5>

<p>Operaciones estadisticas basicas.</p>

In [13]:
#Creando una matriz de numeros random de 2x5
arr = 10 * np.random.randn(2,5)
print(arr)

[[34.17798613  1.41187042  0.50389243 16.59732602  1.12172792]
 [-7.29192887 -3.92367802 -2.84786934 -5.20714928 -8.78997699]]


In [14]:
#Calculando la media de todos los elementos

print(arr.mean())

2.575220041119695


In [15]:
#Calculando la media por cada fila

print(arr.mean(axis = 1))

[10.76256058 -5.6121205 ]


In [16]:
#Calculando la media de cada columna

print(arr.mean(axis = 0))

[13.44302863 -1.2559038  -1.17198845  5.69508837 -3.83412454]


In [17]:
#Sumar todos los elementos

print(arr.sum())

25.75220041119695


In [18]:
#Calcular las medianas (valor medio) de cada fila

print(np.median(arr, axis=1))

[ 1.41187042 -5.20714928]


<p>Clasificacion (ordenamiento).</p>

In [19]:
#Crear un arreglo de 10 elementos randoms

unsorted = np.random.randn(10)

print(unsorted)

[ 0.7998332  -0.82410475  0.05899271  0.60691929  0.27142678  0.76218053
 -0.22081111 -0.04293767  2.32892475 -0.83731819]


In [22]:
#Crear una copia y ordenar

sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)
print()
print(unsorted.shape)

[-0.83731819 -0.82410475 -0.22081111 -0.04293767  0.05899271  0.27142678
  0.60691929  0.76218053  0.7998332   2.32892475]

[ 0.7998332  -0.82410475  0.05899271  0.60691929  0.27142678  0.76218053
 -0.22081111 -0.04293767  2.32892475 -0.83731819]

(10,)


In [24]:
#Ordenando el mismo arreglo sin hacer una copia

unsorted.sort()
print(unsorted)

[-0.83731819 -0.82410475 -0.22081111 -0.04293767  0.05899271  0.27142678
  0.60691929  0.76218053  0.7998332   2.32892475]


<p>Encontrando elementos unicos.</p>

In [25]:
arreglo = np.array([1,2,1,4,2,1,4,2])
print(np.unique(arreglo))

[1 2 4]


<p>Operaciones de conjuntos con np.array tipo de dato.</p>

In [26]:
c1 = np.array(["escritorio", "silla", "tubo"])
c2 = np.array(["lampara", "tubo", "silla"])
print(c1, c2)

['escritorio' 'silla' 'tubo'] ['lampara' 'tubo' 'silla']


In [27]:
#Interseccion de 2 conjuntos

print(np.intersect1d(c1, c2))

['silla' 'tubo']


In [28]:
#union de 2 conjutnos

print(np.union1d( c1, c2))

['escritorio' 'lampara' 'silla' 'tubo']


In [29]:
#Elementos que estan en c1 pero no en c2

print(np.setdiff1d(c1, c2))

['escritorio']


In [31]:
#Que elemento de c1 tambien esta en c2
print(c1)
print(np.in1d(c1, c2))

['escritorio' 'silla' 'tubo']
[False  True  True]


<p>Broadcasting.</p>

In [2]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#Creamos un narreglo de rango 1 con 3 valores

add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [5]:
#Sucamos cada columna de 'start' usando broadcasting

y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [7]:
#Crear un narreglo de 4x1 
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [8]:
#sumamos a cada columna de 'start' usando broadcasting

y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [9]:
#Esto sumara en ambas dimensiones
add_scalar = np.array([1])
print(start + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<p>Ejemplos.</p>

In [12]:
#Crar una matriz de 3x4

matriz = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
#Crear una matriz de 4x1
matrizB = [0,1,0,2]
print(matrizB)

[0, 1, 0, 2]


In [14]:
#Sumar las dos juntas usando broadcasting
print(matriz + matrizB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


<p>test de velocidad: narreglos vs listas.</p>

In [17]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [18]:
#Crear un nareglo con valores 0,1,2..., size-1
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [21]:
#"timer" espera la operacion como un parametro
#pasamos nd_array.sum()

timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Tiempo que tomo por numpy: %f segundos" %
     (timer_numpy.timeit(timeits)/timeits))


Tiempo que tomo por numpy: 0.000919 segundos


In [22]:
#Crear una lista con valores 0,1,2,...,size-1

lista = list(range(size))
print(type(lista))

<class 'list'>


In [24]:

timer_list = Timer("sum(lista)", "from __main__ import lista")

print("Tiempo que tomo:  %f segundos" % 
      (timer_list.timeit(timeits)/timeits))

Tiempo que tomo:  0.057771 segundos


<p>Escribir o leer en disco.</p>
<br>

In [1]:
import numpy as np

x = np.array([23.23, 24.24])

In [4]:
#Formato binario

np.save('arreglo', x)

In [5]:
np.load('arreglo.npy')

array([23.23, 24.24])

In [6]:
#Formato de texto

np.savetxt("arreglo.txt", X=x, delimiter=',')

In [8]:
np.loadtxt("arreglo.txt", delimiter=',')

array([23.23, 24.24])

<p>Operaciones comunes de narreglos adicionales.</p>
<br>
<p>Producto punto en matrices y producto de vectores.</p>

In [15]:
#Calcular el producto punto de dos matrices

x2d = np.array([[1,1], [1,1]])
y2d = np.array([[2,2], [2,2]])

print(x2d)
print()
print(y2d)
print("-"*40)
print(x2d.dot(y2d))
print("-"*40)
print(np.dot(x2d, y2d))

[[1 1]
 [1 1]]

[[2 2]
 [2 2]]
----------------------------------------
[[4 4]
 [4 4]]
----------------------------------------
[[4 4]
 [4 4]]


In [16]:
#Calcular el producto interno de dos vectores

a1d = np.array([9,9])
b1d = np.array([10,10])

print(a1d.dot(b1d))
print("-"*40)
print(np.dot(a1d,b1d))

180
----------------------------------------
180


In [17]:
#Producto puntop de un vector y un arreglo
print(x2d.dot(a1d))
print("-"*40)
print(np.dot(x2d, a1d))

[18 18]
----------------------------------------
[18 18]


<br>
<p>Suma.</p>
<br>

In [18]:
#Sumar elementos de un arreglo

ej1 = np.array([[11,12], [21,22]])

print(np.sum(ej1))

66


In [19]:
#Suma elementos de las columnas

print(np.sum(ej1, axis=0))

[32 34]


In [20]:
#Suma elementos de las filas

print(np.sum(ej1, axis=1))

[23 43]


<p>Otras funciones.</p>

In [21]:
#Comparar 2 arreglos y crear otro con los maximos 

x = np.random.randn(8)
x

array([ 0.36327646, -1.06751602, -1.29254067, -0.23823999,  0.00717195,
        1.85561232,  0.38788635,  0.07719153])

In [22]:
y = np.random.randn(8)
y

array([ 0.6772336 ,  0.94552733, -0.39150829, -1.10579326, -1.49246667,
        0.80039992,  0.3321545 , -1.06328441])

In [23]:
#Devuelve el arreglo de maximos entre los dos arreglos

np.maximum(x, y)

array([ 0.6772336 ,  0.94552733, -0.39150829, -0.23823999,  0.00717195,
        1.85561232,  0.38788635,  0.07719153])

<br>
<p>Reformando arreglo.</p>

In [24]:
#Crear un arreglo de valores del 0 al 19

arreglo = np.arange(20)
print(arreglo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
#Reformando el areglo a una matriz de 4x5
arreglo.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

<p>Transpuesta de una matriz.</p>

In [26]:
#Transpuesta

ej1 = np.array([[11,12], [21,22]])
ej1.T

array([[11, 21],
       [12, 22]])

<p>Indexando usando where().</p>

In [27]:
x1 = np.array([1,2,3,4,5])

y1 = np.array([11,22,33,44,55])

filtro = np.array([True, False, True, False, True])

In [28]:
out = np.where(filtro, x1, y1)
print(out)

[ 1 22  3 44  5]


In [29]:
mat = np.random.rand(5,5)
mat

array([[0.29490446, 0.40497728, 0.30351454, 0.15965273, 0.04835696],
       [0.18329142, 0.56791589, 0.71942574, 0.28648676, 0.57056295],
       [0.40340498, 0.89000025, 0.31382377, 0.93154628, 0.97964105],
       [0.62222545, 0.43925927, 0.63042257, 0.75234751, 0.34399475],
       [0.97885988, 0.94551097, 0.80863246, 0.83383312, 0.85477988]])

In [30]:
np.where( mat > 0.5, 1000, -1)
#Donde es menor a 0.5 pone -1, sino 1000

array([[  -1,   -1,   -1,   -1,   -1],
       [  -1, 1000, 1000,   -1, 1000],
       [  -1, 1000,   -1, 1000, 1000],
       [1000,   -1, 1000, 1000,   -1],
       [1000, 1000, 1000, 1000, 1000]])

<p>Condicionales "any" y "all".</p>

In [37]:
arreglo_booleanos = np.array([ True, False, True, True, False ])

In [33]:
arreglo_booleanos.any()

True

In [38]:
arreglo_booleanos.all()

False

<p>Generacion de numeros al azar.</p>

In [42]:
y = np.random.normal(size = (1,5))[0]
print(y)

[ 0.61364519 -1.13496255  0.57580048  0.15395256  1.55259476]


In [46]:
z = np.random.randint(low=2, high=50, size=(5))
print(z)

[31 24 11  2 27]


In [47]:
np.random.permutation(z)
#devuelve un nuevo orden de z

array([27, 11,  2, 24, 31])

In [50]:
np.random.uniform(size=4)

array([0.82902221, 0.81210099, 0.97619611, 0.37402878])

In [51]:
np.random.normal(size=4)

array([-0.21810175,  0.35561405,  0.87476879,  0.31905176])

<p>Uniendo data sets.</p>

In [54]:
k = np.random.randint(low=2, high=50,size=(2,2))
print(k)

print()
m = np.random.randint(low=2,high=50,size=(2,2))
print(m)

[[46  5]
 [17 30]]

[[11 10]
 [27  8]]


In [55]:
np.vstack((k,m))

array([[46,  5],
       [17, 30],
       [11, 10],
       [27,  8]])

In [56]:
np.hstack((k,m))

array([[46,  5, 11, 10],
       [17, 30, 27,  8]])

In [59]:
np.concatenate([k,m], axis = 0)     #axis = 0

array([[46,  5],
       [17, 30],
       [11, 10],
       [27,  8]])